FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.11

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
RUN apk add --update \
--repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
shairport-sync

COPY start.sh /usr/src/

CMD [ "/bin/bash", "/usr/src/start.sh" ]
