FROM balenalib/%%BALENA_MACHINE_NAME%%:buster

RUN install_packages apt-utils \
  curl \
  && curl -sL https://dtcooper.github.io/raspotify/install.sh | sh

COPY start.sh /usr/src/

CMD [ "/bin/bash", "/usr/src/start.sh" ]
