FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine

ENV INITSYSTEM on

RUN install_packages \
  snapcast \
  avahi \
  dbus

COPY start.sh /usr/src/
WORKDIR /usr/src/
ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

CMD [ "/bin/bash", "start.sh" ]
